export const ADD_OCCUPATION = 'ADD_OCCUPATION';
export const ADD_OCCUPATION_SUCCESS = 'ADD_OCCUPATION_SUCCESS';
export const FETCH_OCCUPATIONS = 'FETCH_OCCUPATIONS';
export const FETCH_OCCUPATIONS_SUCCESS = 'FETCH_OCCUPATIONS_SUCCESS';