export const ADD_PERSON = 'ADD_PERSON';
export const REMOVE_PERSON = 'REMOVE_PERSON';
export const FETCH_PERSONS = 'FETCH_PERSONS';
export const FETCH_PERSONS_SUCCESS = 'FETCH_PERSONS_SUCCESS';
export const FETCH_PERSONS_FAILURE = 'FETCH_PERSONS_FAILURE';
export const API_ADD_PERSON = 'API_ADD_PERSON';
export const API_ADD_PERSON_SUCCESS = 'API_ADD_PERSON_SUCCESS';